### ISSUE TITLE
Only allow tags to be selected from the typeahead dropdown not free text

### ISSUE THREAD

**Issue by HollandRisley** [boneskull/angular-tags#44]
Hi, great work. I would like to use this in a project but I would need to limit user to only select from the typeahead options and not enter free text. Can you advise how I can do this? Also I would like the typeahead to open on focus so user can tab to the field and use down arrow to make selection. Is this easy enough to adapt? If so can you point me in the right direction?

**Comment by boneskull** [comment]
I think you want to pass `allowsEditable: false` to typeahead, assuming the passthrough works.

Not sure about tabbing.  Why not give the tag a `tagindex`?

(Still need to get the new version out.  It's on my list, but since I'm not currently using this in any capacity it's a little difficult to get motivated.)
